# Generated by Django 2.2.3 on 2019-08-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poubelles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField()),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clients', to='laabalpoubelle.Clients')),
                ('poubelles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poubelles', to='laabalpoubelle.Poubelles')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='zones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Zones', to='laabalpoubelle.Zones'),
        ),
    ]
